---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - kvm.cluster.x-k8s.io
  resources:
  - kvmclusters
  - kvmmachines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - kvm.cluster.x-k8s.io
  resources:
  - kvmclusters/finalizers
  - kvmmachines/finalizers
  verbs:
  - update
- apiGroups:
  - kvm.cluster.x-k8s.io
  resources:
  - kvmclusters/status
  - kvmmachines/status
  verbs:
  - get
  - patch
  - update
